### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by wozniakjan** [Cropsey/fsp#1]
#### final steps

- [x] encapsulate engines in panic-recover
- [x] remove anit-bullshit
- [ ] remove printInfo() calls
- [x] test on kiwi servers
- [ ] code cleanup

info:
Keep bottleneck, greedy (they both shut themselves down, greedy if N > 10, bottleneck if no btnck found) and keep the meta engines

SLA*-TSP with prim as heuristics - http://ro.uow.edu.au/cgi/viewcontent.cgi?article=2455&context=theses
ant colony - https://web.tuke.sk/fei-cit/butka/hop/htsp.pdf
